VSoftTechnologies/DUnitX

- DUnitX.Attributes.pas
- DUnitX.Extensibility.pas
- DUnitX.FixtureProviderPlugin.pas
- DUnitX.TestFixture.pas
- DUnitX.TestFramework.pas
- DUnitX.TestRunner.pas
Reason for this change is reducing dependencies a bit.
For a standalone test all you need are the attributes (and the Assert class that is already in its own unit).
> Moved attributes to their own unit

- DUnitX.FixtureProviderPlugin.pas
- DUnitX.IoC.pas
- DUnitX.MemoryLeakMonitor.Default.pas
- DUnitX.TestFramework.pas
- DUnitX.TestRunner.pas
- Tests/DUnitX.Tests.TestNameParser.pas
Made many methods non generic as they are just working with interfaces which can be handled as IInterface.
Also made sure that the delegate already returns the proper type so any further QueryInterface calls are unnecessary.
Used a trick to improve instance creation by taking the codeaddress of the rtti method and casting it to the ctor signature for faster invokation.
Made use of the memoize pattern for capturing the constructor so it only gets queried by rtti once.
Used the same pattern for making sure that a singleton is only created once without any additional checks outside the delegate.
> Quite some refactoring on the container

- DUnitX.TestFramework.pas
- DUnitX.TestRunner.pas
This patch should leave all existing use cases intact while extending the interface reasonably enough so that leak monitors that support textual memory report may take advantage of that.
> added support for extended leak monitors that support memory allocation report

- DUnitX.Init.pas
- DUnitX.TestFramework.pas
- Examples/DUnitXExamples_XE3.dpr
- Examples/DUnitXExamples_XE3.dproj
- README.md
- Tests/DUnitXTest_XE3.dpr
- Tests/DUnitXTest_XE3.dproj
Putting the initialization section into a third unit (DUnitX,Init) seems to solve the problem. 
The extra unit needs to be added only for XE3 projects.
This ~~workaround~~ fixes #117.
> Workaround the Delphi XE3 Compiler Bug

- DUnitX.Attributes.pas
- DUnitX.Extensibility.pas
- DUnitX.FixtureProviderPlugin.pas
- DUnitX.Test.pas
- DUnitX.TestFixture.pas
- DUnitX.TestFramework.pas
- DUnitX.TestRunner.pas
- DUnitX.Timeout.pas
- DUnitX.Utils.pas
- Tests/DUnitX.Tests.TestFixture.pas
- Tests/DUnitXTest_XE7.dpr
- Tests/DUnitXTest_XE7.dproj
First implemented by MartinSedgewick/DUnitX - MaxTimeAttribute
The new attribute allows the user to set the maximum amount of time a test should run. Zero is the default for any test, which means that the timeout will not be tested. The timeout also runs in a seperate thread to make sure it does not interfere with the processing of the test.
> Implemented the Max Timeout attribute for tests.

- DUnitX.Timeout.pas
Previously the timeout exception could be called and the thread was released. Now we wait for and then release the thread ourselves to make sure of its lifecycle.
> Fixed thread timeout exception being called on released thread.

- DUnitX.Timeout.pas
Previously the logic for timeouts was reverse of what it should have been. It now will timeout if the elapsed time is greater than the max time to wait.
> Logic correction for timeouts.

- DUnitX.TestFixture.pas
- DUnitX.Utils.pas
Ajustado erros de compilação quando era ativado o "Emit runtime type information".
> Erros de compilação.

- DUnitX.Utils.pas
A classe TRttiObjectFieldRef, está sem a definição de escopo dos campos da classe, com isso está dando erro de compilação quando o "Emit Runtime Type Information" estiver marcado no projeto.
Apenas coloquei a declaração "public" para parar de dar erro.
> Erro de compilação

- .gitattributes
Per the instructions here:
https://help.github.com/articles/dealing-with-line-endings/
Changing the gitattributes file does not affect the current files (thus
no other file touches are required) but should enforce CRLF as
contributors work on files from this commit forward.
> Enforcing Windows CRLF for line endings

- Examples/DUnitXVCLGUI_D10Berlin.dpr
- Examples/DUnitXVCLGUI_D10Berlin.dproj
- Tests/DUnitXTest_D10Berlin.dpr
- Tests/DUnitXTest_D10Berlin.dproj
The DUnitXTest project file for Berlin wasn't updated with the recent VCL gui logger from #147. So Delphi looked for the DUnitX.Loggers.GUI.pas file, which didn't exist anymore.
Also I created a Berlin project file for the example VCL GUI
> Fixed compilation error in Berlin

- Examples/DUnitXExamples_D10Berlin.dproj
- Examples/DUnitXExamples_D10Seattle.dproj
- Examples/DUnitXExamples_XE2.dproj
- Examples/DUnitXExamples_XE7.dproj
- Examples/DUnitXExamples_XE8.dproj
- Tests/DUnitXTest_D10Berlin.dproj
- Tests/DUnitXTest_D10Seattle.dproj
- Tests/DUnitXTest_XE2.dproj
- Tests/DUnitXTest_XE7.dproj
- Tests/DUnitXTest_XE8.dproj
Replace `DUNITX-DEBUG` in `.dproj` files with  `DUNITXDEBUG` to keep `BRCC32.exe` happy when you add a .RC file to your project. Fixes #158
> Replace `DUNITX-DEBUG` in `.dproj` files with  `DUNITXDEBUG`

- DUnitX.Loggers.GUI.VCL.dfm
EReadError exception using GUI VCL test runner from Delphi XE 1 (Zoom property)
> Fix of issue 176

- DUnitX.AutoDetect.Console.pas
Delphi XE compiler (used via MSBuild in ContinuaCI) is returning following error (non relevant text redacted):
{DelphiBinPath}\CodeGear.Delphi.Targets(188,5): error : E:\ContinuaCi\WorkSpace\Ws\10000\Source\DUnitX\DUnitX.AutoDetect.Console.pas(68) Error: E2029 $IFEND expected but $ENDIF found
{DelphiBinPath}\CodeGear.Delphi.Targets(188,5): error : E:\ContinuaCi\WorkSpace\Ws\10000\Source\DUnitX\DUnitX.Loggers.Console.pas(463) Fatal: F2063 Could not compile used unit 'DUnitX.AutoDetect.Console.pas'
> Correction to work with Delphi XE

- DUnitX.Attributes.pas
- DUnitX.Extensibility.pas
- DUnitX.FixtureProviderPlugin.pas
- DUnitX.Test.pas
- DUnitX.TestFixture.pas
- DUnitX.TestFramework.pas
- DUnitX.Types.pas
- Tests/DUnitX.Tests.Example.pas
like in JUnit the _expected_ attribute allows you to verify that your code throws a specific exception.
Example:
```
[Test('EOutOfMemory')]
procedure FailMe;
procedure TMyTest.FailMe;
begin
OutOfMemoryError;
end;
```
> extended the TestAttribute with "Expected" property

- DUnitX.Assert.pas
Hi there,
calling `Assert.InheritsFrom(TStringList, Exception)` will generate an error message like the following which looks ugly.
> TStringListException does not inherit from .
The proposed change alters the generation of said error message to look like this:
> TStringList does not inherit from Exception.
Regards.
> Correct Error Message for Assert.InheritsFrom with two Classes

- DUnitX.StackTrace.MadExcept4.pas
madStackTrace.StackTrace may produce short stack traces with 64bit builds (only the last frame). Using madExcept.GetCrashStackTrace should enhance these stacks.
> Enhance stack traces with 64-bit builds

- DUnitX.TestFramework.pas
DUnitX.TestFramework.pas
property IFixtureResult.Pesses should be Passes
> Fix typo of property IFixtureResult.Pesses to Passes

- DUnitX.Utils.pas
On line 908 declaration should be `i: NativeInt;` to avoid EOutOfMemory exception in 64-bit as [reported here](https://github.com/VSoftTechnologies/DUnitX/issues/220).
Fixes #220
> fix EOutOfMemory in 64-bit

- DUnitX.Timeout.pas
At least start of an  proper fix on this hint, it seems to be changed in some point. 10.2 at least gives hint if initialization to zero is there.
> 10.2 and up hint fixed

- LiveTemplates/Install.bat
Modificado o instalador do LiveTemplates, para funcionar com a pasta da Embarcadeiro e não apenas com a do Radstudio.
> Live templates

- DUnitX.FixtureProviderPlugin.pas
I think that "i" was intended instead of "x" when calling FormatTestName here.
> fixing wrong var passed into FormatTestName

- DUnitX.Extensibility.pas
- DUnitX.FixtureProviderPlugin.pas
- DUnitX.TestFixture.pas
- DUnitX.TestRunner.pas
- Tests/DUnitX.Tests.IgnoreFixture.pas
Hello,
I implemented the attribute to ignore the complete fixture, which was mentioned in issue: #244 
The fixture is ignored if the ignore attribute is set or if every test in the fixture is ignored.
> Ignore-Attribute for Test-Fixtures

- Tests/DUnitX.Tests.TestDataProvider.pas
I added the missing caseNumber parameter to the GetCaseName function to fix the test project.
> TestDataProvider: Declaration of 'GetCaseName' differs from previous declaration

- Source/DUnitX.Loggers.XML.JUnit.pas
- Tests/DUnitX.Tests.Loggers.XML.JUnit.pas
- Tests/DUnitXTestProject.dpr
- Tests/DUnitXTest_D10Tokyo.dproj
- Tests/DUnitXTest_XE2.dproj
Responding to https://github.com/VSoftTechnologies/DUnitX/issues/258 I have written an XML logger that follows the JUnit format, lending from https://help.catchsoftware.com/display/ET/JUnit+Format
I realized that for _NUnit_, all output format checking tests are disabled, and that if these are enabled, the mockStream.DataString is empty so the assertions fail. I assume that you tend to manually verify the _NUnit_ XML output, e.g. by trying to get it parsed.
I've done the following external verification of the JUnit XML logger:
- Changing the logger used in DUnitXTestProject and verifying that the output looks correct
- Use the JUnit logger in a (closed source) repository where we're using DUnitX, and verify that Gitlab CI properly parses the output. Introduced some errors/failures on …
> JUnit XML logger (Gitlab CI compatibility)

- Source/DUnitX.Windows.Console.pas
I am running this on D2010 and the shorter version runs fine on it.
The {ELSE} actually creates a memory leak which I have not been able to track down:
The block is currently used for an object of class: DUnitX.Windows.Console$ActRec
> Up version to D2010

- Source/DUnitX.Loggers.XML.JUnit.pas
- Summary of test results reported at the "testsuites" node
- report ignored tests as "disabled" on testsuite and fixture level for consistency
> Fix #287 - Summary of JUnit test results should be at the "testsuites" node

- Examples/DUnitX.Examples.General.pas
- Examples/DUnitXExamples_2010.dpr
- Examples/DUnitXExamples_2010.dproj
- Source/DUnitX.Loggers.Text.pas
- Tests/DUnitX.SingleNameSpace.pas
- Tests/DUnitX.Tests.Example.pas
- Tests/DUnitX.Tests.TestNameParser.pas
- Tests/DUnitX.Tests.Utils.pas
- Tests/DUnitXTest_D2010.dpr
- Tests/DUnitXTest_D2010.dproj
Since the company I work at are still on D2010 and we find ourselves using DUnitX more and more I made some fixes so we can execute the tests:
- Create a project for the Delphi 2010 to run the tests.
- Ensure all included files can compile and tests are successful (except the items below)
Issues:
- `DUnitX.Tests.Example.TXampleFixture3` fails, it would seem there is an issue with `[SetupFixture]` with D2010, I have not been able to locate the issue
- `[MaxTime]` also does not seem to work as it hangs the test, I have not investigated further for the time being and flagged the test as `[Ignore]` for D2010
> Updates for Delphi 2010 Tests\Examples

- Source/DUnitX.Loggers.XML.JUnit.pas
- Source/DUnitX.Loggers.XML.NUnit.pas
While TFormatSettings cannot be created in non-XE version (it is a record) it is still passed in the .Format function so it needs to be setup.
The behavior that made me notice the issue is that the time taken for tests in the XML did not have decimals (they seemed to be in ms but in fact simply did not have a decimal separator).
> Fix FormatSetting not getting setup for versions lower than XE

- Expert/DUnitX.Expert.CodeGen.Templates.pas
The IDE (at least that from Delphi 11) remove the $IFNDEF conditional in front of the var section when a unit is added to the test project. As simple comment between the uses section and the conditional prohibits that.
> added comment to protect the TESTINSIGHT conditional

- README.md
Tip taken from a Nov 30th, 2022 Discourse comment from Vicent
> Add tip how to use the GitHub version in replace of the bundled version

- Source/DUnitX.Assert.pas
- Source/DUnitX.ResStrs.pas
- Tests/DUnitX.Tests.Assert.pas
It always bothered me that Assert.NoDiff didn't even attempt to compare when the length of the strings wasn't equal.
Did nobody ever have the case that A is a substring of B or that strings have different lengths but are identical up to a certain position?
Now Assert.NoDiff always compares. If no differences are found and the lengths aren't equal, the remainder is reported as difference.
While working on this, I added Trim() to the FailFmt function in order to get rid of the unnecessary trailing spaces, when no message is passed into the Assert. AFAICT this is not a breaking change for anybody else.
> Improve Assert.NoDiff

- Tests/DUnitX.Tests.Assert.pas
One of the test cases that I converted to the TestCase attribute didn't test what it said it did.
> Fix misnamed test case

- Source/DUnitX.Utils.pas
- Tests/DUnitX.Tests.Example.pas
> TestCaseAttribute does not work with parameters of type UInt64 and values > High(Int64)

- Source/DUnitX.Loggers.XML.NUnit.pas
> Fix TDUnitXXMLNUnitLogger: incorrect value of 'time' attribute of element 'test-results'

- Examples/DUnitXExamples_D10Sydney.dproj
- Examples/DUnitXVCLGUI_D10Berlin.dproj
+ removed redundant DCC_UnitSearchPath override in DUnitXExamples_D10Sydney.dproj
> Fix DUnitXVCLGUI_D10Berlin.dproj compile (File not found "DUnitX.inc")
