Run-Dependend-Delphi-XE7-From-Path.bat
It's a small (somewhat trivial) addition... but since 2010 to XE6 had a Run batch file, I decided to add one for XE7 (updated accordingly)
=> Added batch file for XE7

DUnitX.AutoDetect.Console.pas, DUnitX.Linux.Console.pas
Hi,
I'm working developing unit tests for database components in Embarcadero for R102.
I create the changes required in order to run DUnitX in Linux,
I will appreciate if you could take a look,
=> Changes required to run DUnitX in Linux

DUnitX.Loggers.GUI.VCL.dfm, DUnitX.Loggers.GUI.VCL.pas
I added some functionality to the VCL runner that the checked state of the testcases is stored in an inifile.
=> Save checked testcases to inifile

DUnitX.TestRunner.pas
I've implemented this TODO: "Errors from here need to be logged into each test below us" in DUnitX.TestRunner.pas. 
It is useful when tests have some error in SetupFixture.  Currently, they are not logged. With this change they get logged in each test case result.
=> Log SetupFixture errors in each test case result

DUnitX.TestFramework.pas
Was originally reported [here](https://github.com/VSoftTechnologies/Delphi-Mocks/issues/110)
=> fixed false positive on leak reporting

DUnitX.Loggers.GUI.VCL.dfm, DUnitX.Loggers.GUI.VCL.pas
VCL Logger - Selectable Fixture/Test tree
[https://dl.dropboxusercontent.com/s/gke2kwkuwkzmlvm/vcllogger.jpg?dl=0](https://dl.dropboxusercontent.com/s/gke2kwkuwkzmlvm/vcllogger.jpg?dl=0)
=> VCL Logger - Selectable Fixture/Test tree

Expert/DUnitX.Expert.CodeGen.Templates.pas
=> Apenas mais algumas melhorias.

DUnitX.Attributes.pas
Double `]]` replaced with `)]`
=> MaxTimeAttribute: Small typo in comment

Dependencies.txt
to correspond to Test suite project settings
=> Fix name of Delphi-Mocks repo installed by batch

Source/DUnitX.Test.pas
=> Just solved a hint.

Source/DUnitX.TestRunner.pas
#259 logger missing method
o extract invalidating of test methods inside a fixture
o add missing methods calls to `OnEndTeardownTest` and `OnEndTearDownFixture`
=> #259 logger missing method

Expert/DUnitX.Expert.NewUnitWizardEx.pas, Expert/DUnitX.Expert.ProjectWizardEx.pas, Expert/DUnitX_IDE_Expert_Sydney.dpk, Expert/DUnitX_IDE_Expert_Sydney.dproj
Created project package for Delphi Sydney. I changed the wizzard registration to use the function of all platforms.
=> Sydney support.

Source/DUnitX.Extensibility.pas, Source/DUnitX.FixtureProviderPlugin.pas, Source/DUnitX.TestFixture.pas
=> IgnoreMemoryLeaks attribute does not work

Source/DUnitX.Loggers.XML.JUnit.pas
A stupid oversight of mine ...
=> Fix wrong closing tag in JUnit logger

Expert/DUnitX.Expert.CodeGen.NewTestProject.pas, Expert/DUnitX.Expert.CodeGen.Templates.pas, Expert/DUnitX.Expert.Forms.NewProjectWizard.dfm, Expert/DUnitX.Expert.Forms.NewProjectWizard.pas, Expert/DUnitX.Expert.ProjectWizard.pas, Expert/DUnitX.Expert.ProjectWizardEx.pas
Changed the new project wizard, to select the type of report leak, and create the project with the type selected.
=> Report leak config in the wizard.

Expert/DUnitX.Expert.CodeGen.NewTestProject.pas, Expert/DUnitX.Expert.Forms.NewProjectWizard.pas, Expert/DUnitX.Expert.ProjectWizard.pas, Expert/DUnitX.Expert.ProjectWizardEx.pas
When a unit was added, i didn't compile anymore, because I put the first unit without the comma.
=> Bug in the new project wizard

Source/DUnitX.TestFramework.pas
ExitBehavior now defaults to Continue. See Create.
=> Correcting comment for ExitBehavior

Source/DUnitX.Extensibility.pas
I just implemented the ordering of the results, so that the integration with the IDE gets better.
=> Fixture sorting.

Source/DUnitX.Extensibility.pas
Memory leak is being logged, this solves this problem.
=> Leak reporting.

Source/DUnitX.Utils.pas
=> Removed hints.

Source/DUnitX.Utils.pas, Tests/DUnitX.Tests.Example.pas
=> TestCaseAttribute to support sets

Source/DUnitX.Loggers.GUI.VCL.pas
Replace TIniFIle with TMemIniFile in TGUIVCLTestRunner.FormClose
=> Fix for #354

Source/DUnitX.Loggers.GUI.VCL.pas
Added FTestNodes dict which contains the same TTreeNode items as tvwTests.Items, but much faster to iterate over.
Fixes #358
=> Speed up VCL.GUI logger for large test projects

Source/DUnitX.Loggers.GUI.VCL.pas
=> Added support for Beyond Compare 5
